services:
  - type: web
    name: gdz-photo-bot
    env: python
    plan: free
    region: frankfurt
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m app.main"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: OPENAI_MODEL
        value: "gpt-4.1-mini"
      - key: DAILY_LIMIT
        value: "15"
      - key: WEBHOOK_BASE_URL
        sync: false
      - key: WEBHOOK_PATH
        value: "/webhook-gdz-iluxa"